-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 19:04:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Rede de Hoteis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- QUESTÃO 1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `hotel_nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `quantidade_quartos` INT NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `estrelas` INT NOT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario` (
  `cpf_func` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(10) NOT NULL,
  `ultimo_nome` VARCHAR(10) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `salário` DECIMAL(10,2) NOT NULL,
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `hotel_id_hotel` INT NOT NULL,
  `cargo_id_cargo` INT NOT NULL,
  PRIMARY KEY (`cpf_func`),
  INDEX `fk_funcionario_hotel1_idx` (`hotel_id_hotel` ASC) VISIBLE,
  INDEX `fk_funcionario_cargo1_idx` (`cargo_id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_hotel1`
    FOREIGN KEY (`hotel_id_hotel`)
    REFERENCES `hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_id_cargo`)
    REFERENCES `cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dependentes` (
  `cpf_dependente` INT NOT NULL AUTO_INCREMENT,
  `funcionario_cpf_func` INT NULL,
  `sexo` CHAR(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`cpf_dependente`, `funcionario_cpf_func`),
  INDEX `fk_dependentes_funcionario1_idx` (`funcionario_cpf_func` ASC) VISIBLE,
  CONSTRAINT `fk_dependentes_funcionario1`
    FOREIGN KEY (`funcionario_cpf_func`)
    REFERENCES `funcionario` (`cpf_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_quarto` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `quantidade_camas` INT NOT NULL,
  `qualidade` INT NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quarto` (
  `numero_quarto` INT NOT NULL AUTO_INCREMENT,
  `hotel_id_hotel` INT NOT NULL,
  `disponibilidade` CHAR(1) NOT NULL,
  `tipo_quarto_id_tipo` INT NOT NULL,
  PRIMARY KEY (`numero_quarto`, `hotel_id_hotel`),
  INDEX `fk_quarto_hotel1_idx` (`hotel_id_hotel` ASC) VISIBLE,
  INDEX `fk_quarto_tipo_quarto1_idx` (`tipo_quarto_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_quarto_hotel1`
    FOREIGN KEY (`hotel_id_hotel`)
    REFERENCES `hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quarto_tipo_quarto1`
    FOREIGN KEY (`tipo_quarto_id_tipo`)
    REFERENCES `tipo_quarto` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `nome_meio` CHAR(1) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valor` (
  `calculo_valor` INT NOT NULL,
  `valor_base` INT NOT NULL,
  `serviço_de_quarto` INT NULL,
  `consumiveis` INT NULL,
  `tipo_quarto_id_tipo` INT NOT NULL,
  PRIMARY KEY (`calculo_valor`),
  INDEX `fk_valor_tipo_quarto1_idx` (`tipo_quarto_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_valor_tipo_quarto1`
    FOREIGN KEY (`tipo_quarto_id_tipo`)
    REFERENCES `tipo_quarto` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `dia_reserva` VARCHAR(45) NULL,
  `dia_entrada` VARCHAR(45) NOT NULL,
  `dia_saída` VARCHAR(45) NOT NULL,
  `hotel_id_hotel` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `valor_calculo_valor` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_hotel1_idx` (`hotel_id_hotel` ASC) VISIBLE,
  INDEX `fk_reserva_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_reserva_valor1_idx` (`valor_calculo_valor` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_hotel1`
    FOREIGN KEY (`hotel_id_hotel`)
    REFERENCES `hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_valor1`
    FOREIGN KEY (`valor_calculo_valor`)
    REFERENCES `valor` (`calculo_valor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





-- -----------------------------------------------------
-- QUESTÃO 2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Insert Table `hotel`
-- -----------------------------------------------------
INSERT INTO `hotel` (`hotel_nome`,`endereco`,`cidade`,`quantidade_quartos`,`telefone`,`estrelas`)
VALUES
  ("Topo da Montanha","939-1678 A, Road","Vitória",27,"(27)99512-8548",5),
  ("Canto da Areia","P.O. Box 680, 6315 Arcu. Ave","Vila Velha",21,"(27)99684-9735",4),
  ("A Grande Árvore","Ap #142-7472 Sed Avenue","Vila Velha",25,"(27)99871-7086",5);

-- -----------------------------------------------------
-- Insert Table `cargo`
-- -----------------------------------------------------
INSERT INTO `cargo` (`nome_cargo`)
VALUES
  ("Gerente"),
  ("Arrumeiro"),
  ("Cozinheiro"),
  ("Balconista");

-- -----------------------------------------------------
-- Insert Table `funcionario`
-- -----------------------------------------------------
INSERT INTO `funcionario` (`cpf_func`,`primeiro_nome`,`ultimo_nome`,`data_nascimento`,`sexo`,`salário`,`celular`,`email`,`hotel_id_hotel`,`cargo_id_cargo`)
VALUES
  (74013193060,"Buffy","Cunningham","1993-10-24","H","8365.00","(55)25348-9954","buffy6799@hotmail.com",1,1),
  (08735675012,"Melissa","Hartman","1991-07-18","H","3396.00","(55)72234-1806","melissa750@icloud.com",2,2),
  (90219558060,"Tasha","Mccall","1985-12-08","M","3530.00","(55)41136-3928","tasha@hotmail.com",1,2),
  (47165234039,"Benjamin","Knowles","1977-04-10","M","4766.00","(55)77561-1221","benjamin@hotmail.com",1,3),
  (32074964072,"Prescott","Owens","1970-11-01","H","5896.00","(55)54623-8295","prescott@google.com",1,4),
  (22619399068,"Xyla","Rasmussen","1973-09-03","H","7697.00","(55)74442-4364","xyla2971@icloud.com",2,1),
  (38601549071,"Kevyn","Holt","1990-10-19","H","3179.00","(55)76954-3559","kevyn6907@icloud.com",2,2),
  (83646555076,"Hashim","Pate","1980-06-16","M","3235.00","(55)48076-2013","hashim@icloud.com",2,2),
  (75631257017,"Fleur","Randolph","1975-08-30","M","5780.00","(55)31514-7805","fleur@outlook.com",2,3),
  (95336839027,"Lyle","Tyson","1989-02-16","H","4787.00","(55)81759-7162","lyle@hotmail.com",2,4),
  (76355444033,"Channing","Melton","1982-03-24","H","8568.00","(55)54897-6653","channing4483@google.com",3,1),
  (53256349099,"Kirby","Cohen","1993-07-14","H","3654.00","(55)48932-5123","kirby@outlook.com",3,2),
  (50428588069,"Gwendolyn","Wilcox","1999-09-04","M","3308.00","(55)47885-7853","gwendolyn345@hotmail.com",3,2),
  (33715162023,"Anthony","Dunlap","1987-03-30","M","5886.00","(55)45913-4594","anthony@outlook.com",3,3),
  (96345235016,"Seth","Harmon","1979-09-10","H","4655.00","(55)26668-2699","seth1741@google.com",3,4);
